language: node_js
node_js:
  - "stable"
install:
  - npm install
before_install:
  - npm install express consign body-parser
  - npm install mocha chai supertest mocha-lcov-reporter nyc coveralls --save-dev
after_success:
  - npm run coveralls
